<?php
/**
 * @package    Leytech_RatingStars
 * @author     Chris Nolan (chris@leytech.co.uk)
 * @copyright  Copyright (c) 2017 Leytech
 * @license    https://opensource.org/licenses/MIT  The MIT License  (MIT)
 */
?>
<div class="form-add">
    <h3><?php echo $this->__('Write Your Own Review') ?></h3>
    <div class="block-content">
        <?php if ($this->getAllowWriteReviewFlag()): ?>
        <form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <fieldset>
                <?php echo $this->getChildHtml('form_fields_before')?>
                <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
                    <h4><?php echo $this->__('How do you rate this product?') ?> <em class="required">*</em></h4>
                    <div id="product-review-stars">
                    <?php foreach ($this->getRatings() as $_rating): ?>
                        <dl>
                            <dt class="label"><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></dt>
                            <dd class="rating-input value" id="parentme">
                                <div class="rateYo"></div>
                                <input type="hidden" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_rating" value="" class="" />
                            </dd>
                        </dl>
                    <?php endforeach; ?>
                    </div>

                    <script type="text/javascript">
                        jQuery(function($) {
                            $(".rateYo").rateYo({
                                fullStar: true,
                                onSet: function (rating, rateYoInstance) {
                                    $(this).siblings("input:hidden").val(rating);
                                }
                            });
                        });
                    </script>
                    <span id="input-message-box"></span>
                    <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                <?php endif; ?>
                    <ul class="form-list">
                        <li>
                            <label for="nickname_field" class="required"><em>*</em><?php echo $this->__('Nickname') ?></label>
                            <div class="input-box">
                                <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="<?php echo $this->htmlEscape($data->getNickname()) ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="summary_field" class="required"><em>*</em><?php echo $this->__('Summary of Your Review') ?></label>
                            <div class="input-box">
                                <input type="text" name="title" id="summary_field" class="input-text required-entry" value="<?php echo $this->htmlEscape($data->getTitle()) ?>" />
                            </div>
                        </li>
                        <li>
                            <label for="review_field" class="required"><em>*</em><?php echo $this->__('Review') ?></label>
                            <div class="input-box">
                                <textarea name="detail" id="review_field" cols="5" rows="3" class="required-entry"><?php echo $this->htmlEscape($data->getDetail()) ?></textarea>
                            </div>
                        </li>
                        <li>
                            <?php echo $this->getChildHtml('studioforty9.recaptcha.explicit'); ?>
                        </li>
                    </ul>
                </fieldset>
                <div class="buttons-set">
                    <button type="submit" title="<?php echo $this->__('Submit Review') ?>" class="button"><span><span><?php echo $this->__('Submit Review') ?></span></span></button>
                </div>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var dataForm = new VarienForm('review-form');
            Validation.addAllThese(
            [
                   ['validate-rating', '<?php echo $this->__('Please select your rating above') ?>', function(v) {
                        var dls = $('product-review-stars').select('dl');
                        var inputs;
                        var error = 1;

                        for( var j=0; j < dls.length; j++ ) {
                            var dl = dls[j];
                            inputs = dl.select('input');

                            for( var i=0; i < inputs.length; i++ ) {
                                if( inputs[i].value != "" ) {
                                    error = 0;
                                }
                            }

                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                        return true;
                    }]
            ]
            );
        //]]>
        </script>
        <?php else: ?>
        <p class="review-nologged" id="review-form">
            <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
        </p>
        <?php endif ?>
    </div>
</div>
